basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.shortcuts import render

# Create your views here.
# basic function views to link with each html files newly created
def index(request):
    context_dictionary = {'text': 'hello world', 'number': 50}
    return render(request, 'basic_app/index.html', context_dictionary)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url.html')

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Base page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-link" href="{% url "index" %}">Index</a></li>
                    <li><a class="navbar-link" href="{% url "admin:index" %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url "basic_app:other" %}">Other</a></li>
                    <!-- add link for reltive_url.html here -->
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
                <!-- anything outside of this will be inherited if you extend -->
            {% endblock %}
        </div>
    </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>

<!-- extend from the template that has been created in base.html -->
{% extends "basic_app/base.html" %}
    {% block body_block %}
        {% load custom_templates %}
        <h1>Welcome to index page</h1>
        <h2>Example of template inheritance</h2>
        <!-- contents passed from context_dictionary dictionary of index function of views.py -->
        <!-- upper is a string method, as in Python that converts string to upper case -->
        <h3>{{ text|upper }}</h3>
        <h3>{{ number|add:120 }}</h3>
        <h3>{{ text|cut:"world" }}</h3>
        <h3>{{ number|sqa:20 }}</h3>
        <h3>{{ "value"|upper }}</h3>
    {% endblock %}

templates/basic_app/other.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Other</title>
    </head>
    <body>
        <h1>This is the other page.</h1>
    </body>
</html>

templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Relative Url</title>
    </head>
    <body>
        <h1>This is the relative url page.</h1>
        <!-- in url, basic_app represents the value of app_name global variable that we have set in urls.py of basic_app/urls.py -->
        <!-- other below represents that name of path function that exist in the file that's app_name has been set as basic_app -->
        <a href="{% url 'basic_app:other' %}">Other</a>
        <a href="{% url 'index' %}">Index</a>
        <a href="{% url 'admin:index' %}">Admin</a>
    </body>
</html>